### ISSUE TITLE
Trouble opening saved file

### ISSUE THREAD

**Issue by Tanneguydv** [Tanneguydv/Pythonocc-nodes-for-Ryven#3]
When we load an existing project (`*.json` file) the 3D viewer window launch freeze the load of the project itself.
Conflict between Ryven and the 3D viewer?

The only way I get to open an existing project is to comment this line in `nodes.py`  :

`display, start_display, add_menu, add_functionto_menu = init_display()`
to
`#display, start_display, add_menu, add_functionto_menu = init_display()`

and when the project is loaded uncomment it.

**Comment by leon-thomm** [comment]
It's because you're calling `start_display()` in the `Display_Node`. In the implementation of `init_display()`, for a qt backend, the function `start_display()` they create and return *executes* the qt application
```python
        def start_display() -> None:
            win.raise_()  # make the application float to the top
            app.exec_()
```
and this method call of course never returns (unless you close the app). `init_display()` does check on an existing app instance, which it indeed finds because Ryven created one earlier, but I don't know why they then execute it *again* in `start_display()`, i.e. you should not call `start_display()` in an already running qt app. I removed the call and it seems to work fine now, see PR in a bit...

**Comment by Tanneguydv** [comment]
Wow fast, thank you, I didn't catch it !
